
server:
  port: 10004
spring:
  application:
    name: server-feignhystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 10000